### ISSUE TITLE
assets文件夹没有呢，在哪里获取？

### ISSUE THREAD

**Issue by wisestruct** [Kami-code/dexart-release#11]

**Comment by Kami-code** [comment]
Hi @omengxiang . You can follow the installation instructions [here](https://github.com/Kami-code/dexart-release#installation).

**Comment by wisestruct** [comment]
> Hi @omengxiang . You can follow the installation instructions [here](https://github.com/Kami-code/dexart-release#installation).
谢谢你。你的git仓库里没有assets（tasks annotations, object and robot URDFs），安装指示也没有下载assets的操作呢。

**Comment by Kami-code** [comment]
Hi @omengxiang

> Download the assets from the [Google Drive](https://drive.google.com/file/d/1JdReXZjMaqMO0HkZQ4YMiU2wTdGCgum1/view?usp=sharing) and place the asset directory at the project root directory.
