### ISSUE TITLE
Some issue about model saving

### ISSUE THREAD

**Issue by wslgqq277g** [Kami-code/dexart-release#12]
When I use save function of policy: self.policy.save()，I encounter a issue as following:
 "_generator_ctor() takes from 0 to 1 positional arguments but 2 were given."
However, when i use the saving function of policy without  'data':self_get_constructor_parameters(), It works fine.
Can I just ignore the 'data':self_get_constructor_parameters() when saving the model?

**Comment by Kami-code** [comment]
Hi @wslgqq277g . Thanks for using DexArt. I've added a simple callback function for saving the model while training. Please refer [here](https://github.com/Kami-code/dexart-release/blob/main/stable_baselines3/simple_callback.py) and [here](https://github.com/Kami-code/dexart-release/blob/b5c6522d9d487cf46806bdbba86b83501bfc1f0f/examples/train.py#L126) for more information.
