### ISSUE TITLE
Reason for implementing a different env class for each task despite the high similarity

### ISSUE THREAD

**Issue by jhchong0405** [Kami-code/dexart-release#13]
Hi, thanks for your amazing work! 
I have been checking out this project. Based on my understanding, it seems like the RL environment for the tasks are quite similar (esp. for laptop and toilet), may I know what's your consideration when you choose to implement a new class for each of these task environment instead of using just the base class and modify the config?

**Comment by Kami-code** [comment]
Hi @jhchong0405 . Thanks for using our benchmark. I think this is a common choice for the robotics environment. As you mentioned, you may unify the laptop and toilet environment using the config file, but it's hard to extend to any other possible environment, which harms the extensibility of the benchmark. 

Note: There are still some slight differences in the environment status of the laptop and toilet environments(eg. [here](https://github.com/Kami-code/dexart-release/blob/b5c6522d9d487cf46806bdbba86b83501bfc1f0f/dexart/env/rl_env/toilet_env.py#L68) and [here](https://github.com/Kami-code/dexart-release/blob/b5c6522d9d487cf46806bdbba86b83501bfc1f0f/dexart/env/rl_env/laptop_env.py#L51)).

**Comment by jhchong0405** [comment]
I see. Thanks for the reply!
