### ISSUE TITLE
missing assets? failed to load visual mesh & random lengthy training

### ISSUE THREAD

**Issue by xwong22** [Kami-code/dexart-release#14]
Hi.
It seems like there is an issue with the textured objects of 9918 and 10090, it reports "Failed to load visual mesh" when running random_action.py. Can you please check on this issue?

My temporary solution is to modify the task setting and omit these 2 objects, does this potentially lead to training issues? I have been experiencing random lengthy training epochs that takes a long time on env.step(), which almost looks like it's stuck in a loop.

Thank you in advance for the help!

**Comment by xwong22** [comment]
in the process of debugging the lengthy training time, i discovered that you commented out a few lines in the early stop section [link to code](https://github.com/DLR-RM/stable-baselines3/pull/419)

```python
                if self.target_kl is not None and approx_kl_div > 1.5 * self.target_kl * scheduling:
                    # continue_training = False
                    num_early_stopping += 1
                    # if self.verbose >= 1:
                    #     print(f"Early stopping at step {epoch} due to reaching max kl: {approx_kl_div:.2f}")
                    continue
``` 

these 3 lines are not commented out in the stable baselines3 code [link to code](https://github.com/DLR-RM/stable-baselines3/blob/a9273f968eaf8c6e04302a07d803eebfca6e7e86/stable_baselines3/ppo/ppo.py#L272)

May I know the reasons for commenting out these lines? Thank you!

**Comment by Kami-code** [comment]
Hi, @xwong22 . Thanks for using our benchmark. For your first question, please refer to #1 . For your second question, we comment it out to observe the performance of the designed reward function when the environment is not finalized at the early developing stage(if early stopping happens too frequently, we cannot understand why it works or does not work). I think you can align it with the sb3 version as well and this will not affect the overall performance too much.

**Comment by xwong22** [comment]
I see, thank you so much for the prompt reply!
