### ISSUE TITLE
Assets Google Drive Download Link Missing

### ISSUE THREAD

**Issue by Janebek** [Kami-code/dexart-release#17]
Hi! Great work of yours.

I'm trying to follow the instructions to reproduce your work, but the download link in Google Drive seems to be missing. Could it be that the link has expired?

**Comment by Kami-code** [comment]
Hi @Janebek , Thanks for reminding me. The [link](https://drive.google.com/file/d/1qc-v50eTEjpkRoWsxfqExvC1P_EKSFAa/view?usp=drive_link) has been updated.

**Comment by Janebek** [comment]
Thanks!
