### ISSUE TITLE
NameError: name 'freeze_type' is not defined

### ISSUE THREAD

**Issue by ccmCCMfk** [Kami-code/dexart-release#2]
Thanks for your great work,I have also met some problems ,it seems that new-1.obj had missed,and when I tried
Traceback (most recent call last):
  File "examples/train.py", line 111, in <module>
    if freeze_type > 0:
NameError: name 'freeze_type' is not defined
it affect the training.

**Comment by ccmCCMfk** [comment]
When I tried to annotate them,it works，but I still want to know how to use the freeze_type

**Comment by Kami-code** [comment]
Hi @ccmCCMfk .Thanks for using our benchmark. Now I add the `--freeze` parameter in the train.py. It is used to freeze the visual encoder in the architecture during training. If you want to investigate the performance of some pretrain models without any RL finetune, you can add the parameter into your command. But remember, in our paper all the experiment are conducted with RL finetune. Usually, freezing the visual encoder results poor performance compared to RL finetune one.
