### ISSUE TITLE
"SAPIEN is not responding"

### ISSUE THREAD

**Issue by ccmCCMfk** [Kami-code/dexart-release#3]
And I have another question,when we run python examples/visualize_observation.py --task_name=laptop,is it dynamic or static?
mine is static,and a few seconds later,"SAPIEN is not responding"occurs.

**Comment by Kami-code** [comment]
Hi @ccmCCMfk . Thanks for using our benchmark. We are committed to improving your user experience. Currently, the visualize_observation.py only shows the pointcloud in the first frame. You can move the visualizing function into the loop to visualize pointcloud in each frame.

``` Python
   for i in range(10):
        action = np.random.rand(22)
        obs, reward, done, info = env.step(action)
        pc = visualize_observation(obs, use_seg=False, img_type='robot')
        coordinate = o3d.geometry.TriangleMesh.create_coordinate_frame(size=0.05, origin=[0, 0, 0])
        o3d.visualization.draw_geometries([pc, coordinate], zoom=1,
                                          front=origin - target,
                                          lookat=target,
                                          up=up)
        viewer.render()
```

**Comment by ccmCCMfk** [comment]
Thanks!
