### ISSUE TITLE
Visual pretraining code and dataset

### ISSUE THREAD

**Issue by vlongle** [Kami-code/dexart-release#4]
Hi,

Thank you for your work. The paper mentions that you have a DAM dataset of 6k point clouds which was used to pretrain your pointNet. Is that dataset available anywhere and can you point me to the code for pretraining the encoder?

Thanks!

**Comment by Kami-code** [comment]
Hi @vlongle . Thanks for your interest in our project. The visual pretraining code and dataset is not available now. We will release it as soon as we finish cleaning the code. Maybe in a few days.

**Comment by Kami-code** [comment]
Hi @vlongle . We have uploaded the code to generate dataset and pretrain our models in [examples/pretrain](https://github.com/Kami-code/dexart-release/tree/main/examples/pretrain). You can refer to [examples/pretrain/run.sh](https://github.com/Kami-code/dexart-release/blob/main/examples/pretrain/run.sh) for a detailed usage.
