### ISSUE TITLE
How to evaluate the Success Rate like Table 2 in the paper

### ISSUE THREAD

**Issue by Charlie0257** [Kami-code/dexart-release#5]
Hi, @Kami-code 

Thanks for the wonderful work.
How can I evaluate the success rate like Table 2 in the paper?

Thanks for any help:)

**Comment by Kami-code** [comment]
Hi, @Charlie0257 . Thanks for using our benchmark. We will update the evaluation code in a few days.

**Comment by Kami-code** [comment]
Hi @Charlie0257 . We have uploaded the code to evaluate the policies in [examples/evaluate_policy.py](https://github.com/Kami-code/dexart-release/blob/main/examples/evaluate_policy.py).
