### ISSUE TITLE
assets questions

### ISSUE THREAD

**Issue by zihuuuu** [Kami-code/dexart-release#6]
The assest dataset is missing some files, resulting in code running errors, is there a complete assets dataset.
![fad03baab034b28ec5a46632624472f3](https://github.com/Kami-code/dexart-release/assets/137778660/75e727e0-a791-44ba-b921-5c35fb3fe792)
![08dadbb304b839238a0a7b551d26d2d3](https://github.com/Kami-code/dexart-release/assets/137778660/509c4b2a-8691-46f3-808c-c0b79f755f09)
![b30df76086d57d2e54346e2574c67253](https://github.com/Kami-code/dexart-release/assets/137778660/e66ab6e7-8105-4e46-8941-4d4c2b5aaf24)

**Comment by Kami-code** [comment]
Hi @zihuuuu .You can refer to issue #1 .
