### ISSUE TITLE
How to draw the visual point cloud simulation like in Project?

### ISSUE THREAD

**Issue by Charlie0257** [Kami-code/dexart-release#7]
Hi, @Kami-code 

Thanks for the wonderful work.

Could you please open-source the code to showcase the video for the visual point cloud simulation like in Project?

Thanks for any help:)

**Comment by Kami-code** [comment]
Hi, @Charlie0257 . Thanks for using our benchmark. Currently, the code of rendering pointcloud is not available. We are commited to open-source it in future.
