### ISSUE TITLE
How to produce the task annotation like the project provided?

### ISSUE THREAD

**Issue by Charlie0257** [Kami-code/dexart-release#8]
Hi, @Kami-code 

Thanks for the great work :)
How can I produce the task annotation like the project provided (**e.g., xxx_joint_annotation.json, xxx_scale.json, xxx_allegro_hand_xarm6_wrist_mounted_face_front_relative_position.json**) for other objects from sapien?

Thanks for any help:)

**Comment by Kami-code** [comment]
Hi @Charlie0257 . Thanks for using our benchmark. All the instance annotations used in our project are manually labelled. You can instantiate the new object in the scene to check if your own annotation works or not. See [setup_robot_annotation](https://github.com/Kami-code/dexart-release/blob/2923c6981e6fcb09ccd55f47d8986e33d9aa35af/dexart/env/rl_env/faucet_env.py#L118) and [setup_instance_annotation](https://github.com/Kami-code/dexart-release/blob/2923c6981e6fcb09ccd55f47d8986e33d9aa35af/dexart/env/sim_env/faucet_env.py#L58) for more details.

**Comment by Charlie0257** [comment]
Thanks for your reply!

I will close this issue:)
